# Environment configuration file for anaconda/miniconda
name: courses
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.*
  - pip>=23.0.0
  - setuptools>=59.5.0
  - r-base=4.4.*
  - r-essentials=4.4.*
  - pre-commit=3.8.*
