---
title: |
    | **Fall 2024**
    | **Homework 4**
    | **STAT 656: Bayesian Data Analysis**
author: "Juanwu Lu^[College of Engineering, Purdue University, West Lafayette, IN, USA]"
description: "Homework 4 for STAT 656 at Purdue University"
header-includes:
    - \usepackage{amsmath}
    - \usepackage{amssymb}
    - \usepackage{bbm}
mainfont: Times New Roman
output:
    pdf_document: default
fig_width: 6
fig_height: 4
editor_options:
  markdown:
    wrap: 79
---

```{r setup, include=FALSE}
library(bayesplot)
library(dplyr)
library(ggplot2)
library(moments)
library(patchwork)
library(rstan)
library(tidyr)
bayesplot_theme_set(theme_default(base_size = 12, base_family = "sans"))
```

# Gibbs Sampling for Probit Model

Consider $N$ pairs of observations $(x_{i},y_{i})$, where $x_{i}\in\mathbf{R}^{d}$ and $y_{i}\in\left\{0, 1\right\}$. These are generated as follows:
$$
z_{i}\sim\mathcal{N}(x_{i}\beta,1)\quad y_{i}=\mathbbm{1}(z_{i}> 0),\quad i=1,\ldots,N 
$$
This is thus the probit model fro the Lecture slides. Write $X$, $Y$, and $Z$ for the collection of $x_{i}$, $y_{i}$, and $z_{i}$'s. We will place a $\mathcal{N}(0,\Sigma_{b})$ prior on $\beta\in\mathbb{R}^{d}$, and draw samples from the posterior $p(\beta,Z\mid X,Y)$. Observe that as in regression settings, we are really only interested in $\beta$, the $Z$'s only auxiliary variables to allow us to implement a Gibbs sampler. In other words, this is an example of a *data-augmentation algorithm*.

1. (7 points) Derive and write down the conditional distribution $p(Z\mid X,Y,\beta)$.
2. (7 points) Derive and write down the conditional distribution $p(\beta\mid X,Y,Z)$?
3. (1 points) Describe the overall Gibbs sampling algorithm, and how you would calculate the posterior mean and covariance of $\beta$.
4. (20 points) Write an R function that implement the VB algorithm for the probit model given in the slides. This should accept as input a dataset $(X, Y)$ and return the approximations to the posterior distribution over $\beta$ and the $z$'s. Recall how the algorithm proceeds: start with some arbitrary initial distribution $q(\beta)$ over $\beta$, use that to calculate the $q(z_{i})$'s, use those to calculate $q(\beta)$, and repeat till these distributions stop changing.

**Solution:**

1. The conditional distribution $Z\mid X, Y,\beta$ is derived as follows:
$$
\tag{1}
\begin{aligned}
  \log{p}(Z|X,Y,\beta) &= \log{p}(\beta) + \sum\limits_{i=1}^{N}\log{p}(y_{i}\mid z_{i}) + \log{p}(z_{i}\mid x_{i}) + C_{1} \\
  &= -\frac{1}{2}\beta^{T}\Sigma_{b}^{-1}\beta + \sum\limits_{i=1}^{N}y_{i}\log\mathbbm{1}(z_{i}>0) + (1-y_{i})\log\mathbbm{1}(z_{i}\leq 0) - \frac{1}{2}\left(z_{i}-x_{i}\beta\right)^{2} + C_{2}
\end{aligned}
$$
Therefore, the conditional distribution is given by:
$$
\tag{2}
p(z_{i}|x_{i},y_{i},\beta)\propto\begin{cases}
  \mathbbm{1}(z_{i}>0)\mathcal{N}(x_{i}\beta,1) & \text{if } y_{i}=1, \\
  \mathbbm{1}(z_{i}\leq 0)\mathcal{N}(x_{i}\beta,1) & \text{otherwise.}
\end{cases}
$$

2. Based on the results from equation (1), the conditional distribution of $\beta\mid X,Y,Z$ is derived by:
$$
\begin{aligned}
\log{p}(\beta\mid X,Y,Z) &= -\frac{1}{2}\sum\limits_{i=1}^{d}z_{i}^{2}-2z_{i}(x_{i}\beta) + x_{i}\beta\beta^{\intercal}x_{i}^{\intercal} + \beta^{\intercal}\Sigma_{b}^{-1}\beta + C_{3} \\
&= -\frac{1}{2}\beta^{\intercal}\left(\sum\limits_{i=1}^{N}x_{i}^{\intercal}x_{i}+\Sigma_{b}^{-1}\right)\beta - 2\sum\limits_{i=1}^{N}z_{i}x_{i}\beta + C_{4} \\
&= -\frac{1}{2}\left(\beta-\Sigma_{\beta\mid X,Y,Z}\sum\limits_{i=1}^{N}z_{i}x_{i}^{\intercal}\right)^{\intercal}\Sigma_{\beta\mid X,Y,Z}^{-1}\left(\beta-\Sigma_{\beta\mid X,Y,Z}\sum\limits_{i=1}^{N}z_{i}x_{i}^{\intercal}\right) + C_{5}, \\
\text{where}\quad & \Sigma_{\beta\mid X,Y,Z} = \left(\sum\limits_{i=1}^{N}x_{i}^{\intercal}x_{i}+\Sigma_{b}^{-1}\right)^{-1}
\end{aligned}
$$
Therefore, the conditional distribution is a multivariate normal distribution
$$
\tag{2}
p(\beta\mid X,Y,Z)\sim\mathcal{N}\left(\left(\sum\limits_{i=1}^{N}x_{i}^{\intercal}x_{i}+\Sigma_{b}^{-1}\right)^{-1}\sum\limits_{i=1}^{N}z_{i}x_{i}^{\intercal}, \left(\sum\limits_{i=1}^{N}x_{i}^{\intercal}x_{i}+\Sigma_{b}^{-1}\right)^{-1}\right)
$$

3. The Gibbs sampling algorithm is as follows:
- Initialize $\beta$ and $Z$.
- Repeat the following steps until convergence or a maximum number of iterations:
  - Sample $Z\mid X,Y,\beta$ from the conditional distribution $p(Z\mid X,Y,\beta)$.
  - Sample $\beta\mid X,Y,Z$ from the conditional distribution $p(\beta\mid X,Y,Z)$.
Therefore, with every sampled collection of $Z$, we can calculate the posterior mean and covariance of $\beta$ according to the results equation ($2$):
- Calculate the covariance by $\left(\sum\limits_{i=1}^{d}x_{i}^{\intercal}x_{i}+\Sigma_{b}^{-1}\right)^{-1}$.
- Calculate the mean by $\left(\sum\limits_{i=1}^{d}x_{i}^{\intercal}x_{i}+\Sigma_{b}^{-1}\right)^{-1}\sum\limits_{i=1}^{d}z_{i}x_{i}^{\intercal}$, where $z_{i}$ are samples from the first step of Gibbs sampling iterations.

4. The mean-field variational family of the original model is given by $q(\beta,z)=q(\beta)\prod\limits_{i=1}^{N}q(z_{i})$, where the optimal formula for the two variational distributions are given by:
$$
\begin{aligned}
  \log{q}^{*}(Z) &= \mathbb{E}_{q(\beta)}\left[\log{p}(Y,Z,\beta|x)\right] \\
  &= \mathbb{E}_{q(\beta)}\left[-\frac{1}{2}\beta^{T}\Sigma_{b}^{-1}\beta + \sum\limits_{i=1}^{N}y_{i}\log\mathbbm{1}(z_{i}>0) + (1-y_{i})\log\mathbbm{1}(z_{i}\leq 0) - \frac{1}{2}\left(z_{i}-x_{i}\beta\right)^{2} + C_{2}\right] \\
  &= \sum\limits_{i=1}^{N}y_{i}\log\mathbbm{1}(z_{i}>0) + (1-y_{i})\log\mathbbm{1}(z_{i}\leq 0) - \frac{1}{2}\left(z^{2}_{i}-2x_{i}\mu_{\beta}z_{i}\right) + C_{6}, \\
  \text{where,}\quad \mu_{\beta} &= \mathbb{E}_{q(\beta)}[\beta].
\end{aligned}
$$
Therefore, the variational distribution of $Z$ is given by
$$
  q(Z) = \prod\limits_{i=1}^{N}\mathbbm{1}(z_{i}>0)^{y_{i}}\mathbbm{1}(z_{i}\leq 0)^{1-y_{i}}\mathcal{N}(x_{i}\mu_{\beta},1).
$$
Similarly, the optimal formula for the distribution of $\beta$ is given by:
$$
\begin{aligned}
  \log{q}^{*}(\beta) &= \mathbb{E}_{q(Z)}[\log{p}(Y,Z,\beta|x)] \\
  &= \mathbb{E}_{q(Z)}\left[-\frac{1}{2}\beta^{T}\Sigma_{b}^{-1}\beta + \sum\limits_{i=1}^{N}y_{i}\log\mathbbm{1}(z_{i}>0) + (1-y_{i})\log\mathbbm{1}(z_{i}\leq 0) - \frac{1}{2}\left(z_{i}-x_{i}\beta\right)^{2} + C_{2}\right] \\ 
  &= -\frac{1}{2}\beta^{\intercal}\Sigma_{b}^{-1}\beta -\frac{1}{2}\sum\limits_{i=1}^{N}\left(\beta^{\intercal}x_{i}^{\intercal}x_{i}\beta - 2\mu_{z_{i}}x_{i}\beta \right) + C_{7}
\end{aligned}
$$
Therefore, the variational distribution of $\beta$ is given by
$$
q(\beta) = \mathcal{N}\left(\Sigma_{q}\left(\sum\limits_{i=1}^{N}\mu_{z_{i}}x_{i}^{\intercal}\right), \Sigma_{q}\right),\quad\text{where }\Sigma_{q} = \left(\sum\limits_{n=1}^{N}x_{i}^{\intercal}x_{i} + \Sigma_b\right)^{-1}
$$

\pagebreak

# Effect of Computer-generated Reminders

